services:
  app:
    build:
      context: .
    container_name: shaukat_app
    restart: always
    volumes:
      - .:/usr/src/app      
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
      - ./prisma/dev.db:/usr/src/app/prisma/dev.db

  nginx:
    image: nginx:alpine
    container_name: shaukat_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app